// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripLog.Models;

#nullable disable

namespace TripLog.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20220328134854_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TripLog.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccomidationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomidationPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accomidations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThingsToDo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThingsToDo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThingsToDo3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccomidationEmail = "resortworld@resort.com",
                            AccomidationPhone = "475-890-1234",
                            Accomidations = "Resort World",
                            Destination = "Puerto Rico",
                            EndDate = "05/27/2021",
                            StartDate = "05/20/2021",
                            ThingsToDo1 = "visit beach",
                            ThingsToDo2 = "have a margarita",
                            ThingsToDo3 = "tan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
